# Main Prompt Format
# ==================
format = """
[](#c8c093)\
$os$username[@](bg:#c8c093 fg:#16161D)$hostname\
[](bg:#7e9cd8 fg:#c8c093)\
$directory\
[](bg:#6a9589 fg:#7e9cd8)\
$git_branch$git_commit$git_state$git_metrics$git_status\
[](bg:#98bb6c fg:#6a9589)\
$package$c$cmake$cobol$daml$dart$deno$dotnet$elixir$elm$erlang$fennel$gleam\
$golang$guix_shell$haskell$haxe$helm$java$julia$kotlin$gradle$lua$nim$nodejs\
$ocaml$opa$perl$php$pulumi$purescript$python$quarto$raku$rlang$red$ruby$rust\
$scala$solidity$swift$terraform$typst$vlang$vagrant$zig\
[](bg:#dcd7ba fg:#98bb6c)\
$cmd_duration\
[](fg:#dcd7ba)\
$line_break\
$character
"""

# OS
# ===
[os]
style = "fg:#16161D bg:#c8c093"
disabled = false

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = " "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

# User and Host Information
# =========================
[hostname]
ssh_only = false
style = "fg:#16161D bg:#c8c093"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = " "

[username]
show_always = true
format = '[$user]($style)'
style_user = "fg:#16161D bg:#c8c093"

# Directory
# =========
[directory]
style = "fg:#16161D bg:#7e9cd8"
read_only = " "
format = "[ 󰉋 $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:#16161D bold bg:#7e9cd8"

# Git Information
# ===============
[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "󰘬 "
style = "fg:#16161D bg:#6a9589"

[git_status]
style = "bg:teal"
format = '[[($all_status$ahead_behind )](fg:#16161D bg:#6a9589)]($style)'

# Languages
# =========
[nodejs]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:#16161D bg:#98bb6c)]($style)'

[c]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:#16161D bg:#98bb6c)]($style)'

[rust]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:#16161D bg:#98bb6c)]($style)'

[golang]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:#16161D bg:#98bb6c)]($style)'

[php]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:#16161D bg:#98bb6c)]($style)'

[java]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:#16161D bg:#98bb6c)]($style)'

[kotlin]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:#16161D bg:#98bb6c)]($style)'

[haskell]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:#16161D bg:#98bb6c)]($style)'

[lua]
symbol = '󰢱 '
format = '[ $symbol($version )]($style)'
style = "fg:#16161D bg:#98bb6c"

[python]
symbol = '󰌠 '
format = "[ $symbol($version )]($style)"
style = "fg:#16161D bg:#98bb6c"

# Miscellaneous
# =============
[cmd_duration]
format = "[ 󰔚 $duration ]($style)"
style = "fg:#16161D bg:#dcd7ba"

[character]
success_symbol = "[ 󱞩](bold #98bb6c)"
error_symbol = "[ 󱞩](bold #e82424)"
vimcmd_symbol = "[  󱞩](bold #98bb6c)"

